import 'package:los_hambrientos/src/features/products/domain/product.dart';

/// Test products to be used until a data source is implemented
const kTestProducts = [
  Product(
    id: '1',
    imageUrl: 'assets/products/burger_1.jpg',
    title: 'Burger de Souleymane',
    description: 'Lorem ipsum',
    price: 15,
    availableQuantity: 5,
    avgRating: 4.5,
    numRatings: 2,
  ),
  Product(
    id: '2',
    imageUrl: 'assets/products/burger_2.jpg',
    title: 'Burger de Soukeyna',
    description: 'Lorem ipsum',
    price: 13,
    availableQuantity: 5,
    avgRating: 4,
    numRatings: 2,
  ),
  Product(
    id: '3',
    imageUrl: 'assets/products/burger_3.jpg',
    title: 'Burger d\'Amy',
    description: 'Lorem ipsum',
    price: 17,
    availableQuantity: 5,
    avgRating: 5,
    numRatings: 2,
  ),
  Product(
    id: '4',
    imageUrl: 'assets/products/burger_4.jpg',
    title: 'Burger de Fatime',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 5,
  ),
  Product(
    id: '5',
    imageUrl: 'assets/products/burger_5.jpg',
    title: 'Burger d\'Idriss',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '6',
    imageUrl: 'assets/products/burger_6.jpg',
    title: 'Burger de Gabriel',
    description: 'Lorem ipsum',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '7',
    imageUrl: 'assets/products/burger_7.jpg',
    title: 'Burger de Caroline',
    description: 'Lorem ipsum',
    price: 18,
    availableQuantity: 10,
  ),
  Product(
    id: '8',
    imageUrl: 'assets/products/burger_8.jpg',
    title: 'Burger pour les petits joueurs',
    description: 'Lorem ipsum',
    price: 21,
    availableQuantity: 10,
  ),
  Product(
    id: '9',
    imageUrl: 'assets/products/burger_9.jpg',
    title: 'Burger pour les grands joueurs',
    description: 'Lorem ipsum',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '10',
    imageUrl: 'assets/products/burger_10.jpg',
    title: 'Burger aux olives',
    description: 'Lorem ipsum',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '11',
    imageUrl: 'assets/products/burger_11.jpg',
    title: 'Burger aux oignons',
    description: 'Lorem ipsum',
    price: 24,
    availableQuantity: 10,
  ),
  Product(
    id: '12',
    imageUrl: 'assets/products/burger_12.jpg',
    title: 'Burger au pain noir',
    description: 'Lorem ipsum',
    price: 22,
    availableQuantity: 10,
  ),
  Product(
    id: '13',
    imageUrl: 'assets/products/burger_13.jpg',
    title: 'Burger de Sékou',
    description: 'Lorem ipsum',
    price: 14,
    availableQuantity: 10,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/products/burger_14.jpg',
    title: 'Burger de papi Bakary',
    description: 'Lorem ipsum',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/products/burger_15.jpg',
    title: 'Burger de Bintou',
    description: 'Lorem ipsum',
    price: 16,
    availableQuantity: 10,
  ),
];
